version: '1.9.7.{build}'

configuration: Release
platform: Any CPU
image:
- Ubuntu1804

shallow_clone: true

build: off
skip_tags: true

for:

# Linux Build:
  -
    matrix:
      only:
        - image: Ubuntu1804

    install:
    - sh: docker pull lonosproject/lonos-build || docker pull lonosproject/lonos-build # with retry, if failed

    before_build:
    - echo test

    build: off

    build_script:
    - sh: echo UID "$UID"
    - sh: docker run --name lonos -v $APPVEYOR_BUILD_FOLDER:/home/appveyor lonosproject/lonos-build /bin/bash -c "useradd -m -u $UID appveyor && su appveyor -- -c 'cd /home/appveyor && chmod +x lonosctl && ./lonosctl test cloud'"
